os: linux
dist: xenial

language: cpp
compiler: gcc

env: PATH=$PATH:${TRAVIS_BUILD_DIR}/src/

install:
  - git clone https://github.com/Lartu/ldpltest

script:
  - cd src && make
  - cd ../ldpltest && ./compileAndRunTester.sh | grep "ALL TESTS PASSED SUCCESSFULLY"
